"""Generate committed ANTLR-derived parser code.

This script is intended for contributors only.

Policy:
- Grammar sources live in `grammars/`.
- Generated Python code is committed under `openehr_am/_generated/`.
- End-users installing the package should NOT need Java or ANTLR.

Prerequisites (contributors):
- Java (a `java` executable on PATH)
- ANTLR tool jar (e.g. `antlr-4.13.2-complete.jar`)

See `docs/dev/parsers.md` for details.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path


def _find_antlr_grammars(grammars_dir: Path) -> list[Path]:
    return sorted(grammars_dir.rglob("*.g4"))


def _find_java() -> str | None:
    return shutil.which("java")


def _resolve_antlr_jar(*, cli_value: str | None) -> Path | None:
    raw = cli_value or os.environ.get("ANTLR4_JAR")
    if not raw:
        return None
    jar = Path(raw).expanduser()
    if not jar.exists() or not jar.is_file():
        raise ValueError(f"ANTLR jar not found: {jar}")
    return jar


def _ensure_generated_package_scaffold(tmp_out: Path) -> None:
    # Deterministic package marker so generated code is importable.
    init_py = tmp_out / "__init__.py"
    init_py.write_text(
        "# Generated by scripts/generate_parsers.py; do not edit.\n",
        encoding="utf-8",
    )


def _run_antlr(
    *,
    java: str,
    antlr_jar: Path,
    grammars: list[Path],
    grammars_dir: Path,
    out_dir: Path,
) -> None:
    # Keep the invocation deterministic:
    # - sorted grammar list
    # - exact output dir
    # - pinned language target
    cmd: list[str] = [
        java,
        "-jar",
        str(antlr_jar),
        "-Dlanguage=Python3",
        "-encoding",
        "UTF-8",
        "-listener",
        "-visitor",
        "-Xexact-output-dir",
        "-o",
        str(out_dir),
        "-package",
        "openehr_am._generated",
        "-lib",
        str(grammars_dir),
        *[str(p) for p in grammars],
    ]

    subprocess.run(cmd, check=True)


def _sync_generated_tree(*, tmp_out: Path, generated_dir: Path) -> None:
    # Remove previously generated artefacts but keep README.md (and any other
    # hand-written documentation).
    for child in generated_dir.iterdir():
        if child.name == "README.md":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()

    # Copy new output in.
    for src in tmp_out.rglob("*"):
        rel = src.relative_to(tmp_out)
        dst = generated_dir / rel

        if src.is_dir():
            dst.mkdir(parents=True, exist_ok=True)
            continue

        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Generate ANTLR-derived Python parser code into openehr_am/_generated/. "
            "If no grammars are present, this is a no-op."
        ),
    )
    parser.add_argument(
        "--antlr-jar",
        help=(
            "Path to the ANTLR tool jar (e.g. antlr-4.13.2-complete.jar). "
            "Alternatively set ANTLR4_JAR."
        ),
    )
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    grammars_dir = repo_root / "grammars"
    generated_dir = repo_root / "openehr_am" / "_generated"

    if not grammars_dir.exists():
        print(
            "scripts/generate_parsers.py: no grammars/ directory; nothing to generate"
        )
        return 0

    if not generated_dir.exists():
        raise SystemExit(
            "openehr_am/_generated/ is missing. Create it and commit generated code."
        )

    grammars = _find_antlr_grammars(grammars_dir)
    if not grammars:
        print("scripts/generate_parsers.py: no *.g4 grammars; nothing to generate")
        return 0

    try:
        antlr_jar = _resolve_antlr_jar(cli_value=args.antlr_jar)
    except ValueError as exc:
        print(f"scripts/generate_parsers.py: {exc}", file=sys.stderr)
        return 2

    if antlr_jar is None:
        print(
            "scripts/generate_parsers.py: ANTLR tool jar not configured. "
            "Set ANTLR4_JAR or pass --antlr-jar. "
            "See docs/dev/parsers.md.",
            file=sys.stderr,
        )
        return 2

    java = _find_java()
    if java is None:
        print(
            "scripts/generate_parsers.py: Java not found on PATH (missing `java`). "
            "See docs/dev/parsers.md.",
            file=sys.stderr,
        )
        return 2

    with tempfile.TemporaryDirectory(prefix="openehr_am_antlr_") as tmp:
        tmp_out = Path(tmp) / "out"
        tmp_out.mkdir(parents=True, exist_ok=True)

        try:
            _run_antlr(
                java=java,
                antlr_jar=antlr_jar,
                grammars=grammars,
                grammars_dir=grammars_dir,
                out_dir=tmp_out,
            )
        except subprocess.CalledProcessError as exc:
            print(
                f"scripts/generate_parsers.py: ANTLR generation failed (exit {exc.returncode}).",
                file=sys.stderr,
            )
            return 1
        _ensure_generated_package_scaffold(tmp_out)
        _sync_generated_tree(tmp_out=tmp_out, generated_dir=generated_dir)

    print(
        "scripts/generate_parsers.py: generated output updated in openehr_am/_generated/"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
